//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 办公系统
//  @ File Name : CmConfig.java
//  @ Date : 2007-11-9
//  @ Author :
//
//



package openwd.util;
import openwd.util.ConfigFile;

/**
 * 读取配置文件。
 **/
public class OpenConfig {
  /** */
  public OpenConfig() {
  }



  /** */
  public static String getkeyvalue(String key) {

    return ConfigFile.getInstance().getkeyvalue(key);
  }

}